// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package queries

import (
	"context"
)

const getMemory = `-- name: GetMemory :one
SELECT public_key, content, updated_at FROM agent_user_memories
WHERE public_key = $1
`

func (q *Queries) GetMemory(ctx context.Context, publicKey string) (*AgentUserMemory, error) {
	row := q.db.QueryRow(ctx, getMemory, publicKey)
	var i AgentUserMemory
	err := row.Scan(&i.PublicKey, &i.Content, &i.UpdatedAt)
	return &i, err
}

const upsertMemory = `-- name: UpsertMemory :exec
INSERT INTO agent_user_memories (public_key, content, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (public_key) DO UPDATE
SET content = $2, updated_at = NOW()
`

type UpsertMemoryParams struct {
	PublicKey string `json:"public_key"`
	Content   string `json:"content"`
}

func (q *Queries) UpsertMemory(ctx context.Context, arg *UpsertMemoryParams) error {
	_, err := q.db.Exec(ctx, upsertMemory, arg.PublicKey, arg.Content)
	return err
}
