// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentMessageRole string

const (
	AgentMessageRoleUser      AgentMessageRole = "user"
	AgentMessageRoleAssistant AgentMessageRole = "assistant"
	AgentMessageRoleSystem    AgentMessageRole = "system"
)

func (e *AgentMessageRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentMessageRole(s)
	case string:
		*e = AgentMessageRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentMessageRole: %T", src)
	}
	return nil
}

type NullAgentMessageRole struct {
	AgentMessageRole AgentMessageRole `json:"agent_message_role"`
	Valid            bool             `json:"valid"` // Valid is true if AgentMessageRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentMessageRole) Scan(value interface{}) error {
	if value == nil {
		ns.AgentMessageRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentMessageRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentMessageRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentMessageRole), nil
}

type AgentConversation struct {
	ID         pgtype.UUID        `json:"id"`
	PublicKey  string             `json:"public_key"`
	Title      pgtype.Text        `json:"title"`
	Summary    pgtype.Text        `json:"summary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AgentMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           AgentMessageRole   `json:"role"`
	Content        string             `json:"content"`
	ContentType    string             `json:"content_type"`
	AudioUrl       pgtype.Text        `json:"audio_url"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
